### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by hungnguyen2611** [yrcong/flatten#1]

**Comment by hungnguyen2611** [comment]
incredible work, any plans for releasing the code

**Comment by yrcong** [comment]
> incredible work, any plans for releasing the code 

thanks for you interest😁We are going to release the code in Nov.

**Comment by leoShen917** [comment]
Excellent work, looking forward to your code!

**Comment by xavierp7** [comment]
Hello! The FLATTEN work is very excellent but I am wondering when you plan to release the code.  I noticed you said November but it's nearing the end of the month already.

**Comment by yrcong** [comment]
Sorry, I was busy with some tasks as well as interviews 🫨 so I have to postpone it. Thanks for your interest and giving me a boost！I will try my best and make it open as fast as possible👨‍💻

**Comment by yrcong** [comment]
> Hello! The FLATTEN work is very excellent but I am wondering when you plan to release the code. I noticed you said November but it's nearing the end of the month already.

Hi! The code is under review now and should be available soon:)

**Comment by leoShen917** [comment]
> Hi! The code is under review now and should be available soon:)

I can't wait to try and experience such a great work! Hope it will be released soon, thank you very much!

**Comment by leoShen917** [comment]
Sorry to bother you, now the end of the year, do you plan to release the code this year?

**Comment by yrcong** [comment]
> Sorry to bother you, now the end of the year, do you plan to release the code this year?

Actually, it's not up to me since the project is done at Meta. If you need this code urgently for **research**, please email me (congyuren@hotmail.com).
